# Generated by Django 4.0.4 on 2022-06-06 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(max_length=50)),
                ('end', models.CharField(max_length=50)),
                ('day', models.DateField()),
                ('earliest_start_time', models.TimeField()),
                ('latest_start_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('price', models.FloatField()),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='prices', to='cost_monitor.connection')),
            ],
        ),
        migrations.AddField(
            model_name='connection',
            name='journey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='connections', to='cost_monitor.journey'),
        ),
    ]
